# Generated by Django 5.0.2 on 2024-04-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0002_archive_delete_archiveentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='archive',
            name='category',
            field=models.CharField(default='texts', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archive',
            name='tags',
            field=models.CharField(default='fun', max_length=200),
            preserve_default=False,
        ),
    ]
