# Generated by Django 5.0.2 on 2024-04-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0004_archive_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='user',
        ),
    ]
